version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[GitHub Actions] "
    open-pull-requests-limit: 10
    reviewers:
      - "matomo-org/core-reviewers"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      all-submodules:
        patterns:
         - "*"
    commit-message:
      prefix: "[Submodules] "
    reviewers:
      - "matomo-org/core-reviewers"
    pull-request-branch-name:
      separator: "-" 

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "[NPM] "
    reviewers:
      - "matomo-org/core-reviewers"
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/tests/lib/screenshot-testing"
    schedule:
      interval: "monthly"
    labels:
      - "c: Tests & QA"
    groups:
      all-dependencies:
        patterns:
         - "*"
    commit-message:
      prefix: "[NPM UI Tests] "
    reviewers:
      - "matomo-org/core-reviewers"
    pull-request-branch-name:
      separator: "-"    
    versioning-strategy: lockfile-only
