version: '2'
volumes:
  database:
networks:
  back:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
services:
  db:
    image: mysql:5.6
    volumes:
      - database:/var/lib/mysql
      - ./misc/docker/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_DATABASE: matomo
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: matomo
    networks:
    - back
  matomo:
    image: matomo:3.8.1-apache-dev
    build:
      context: .
      dockerfile: ./misc/docker/Dockerfile-matomo-3.8.1-apache-dev
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./:/var/www/html
    environment:
      APACHE_RUN_USER: '#1000'
      XDEBUG_CONFIG: 'remote_enable=1 remote_host=192.168.220.1 remote_autostart=1 idekey=PHPSTORM'
      PHP_IDE_CONFIG: 'serverName=Docker'
    networks:
      - back
      - front
