name: PHP Tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: write
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none


jobs:
  php74:
    runs-on: ubuntu-20.04

    services:
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options:  >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: piwik_tests
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --tmpfs /var/lib/mysql:rw
    strategy:
      fail-fast: false
      matrix:
        tests: [ 'UnitTests', 'SystemTestsPlugins' ,'SystemTestsCore' , 'IntegrationTestsCore','IntegrationTestsPlugins' ]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          lfs: false
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: bcmath, ldap, curl, zip, pdo_mysql, mysqli, gd, redis
          ini-values: post_max_size=256M, max_execution_time=10000, memory_limit=-1, always_populate_raw_post_data=-1, error_reporting=E_ALL, log_errors=on, display_errors=on, zend.exception_ignore_args = Off
          tools: composer:v2
          coverage: none

      - name: installing config.ini.php && Adjusting phpunit.xml && tmp/ sub-directories
        run: |
          php -i
          cp .github/scripts/config.ini.github.php  config/config.ini.php
          cp ./tests/PHPUnit/phpunit.xml.dist ./tests/PHPUnit/phpunit.xml
          mkdir -p ./tmp/assets
          mkdir -p ./tmp/cache
          mkdir -p ./tmp/cache/tracker
          mkdir -p ./tmp/latest
          mkdir -p ./tmp/logs
          mkdir -p ./tmp/sessions
          mkdir -p ./tmp/templates_c
          mkdir -p ./tmp/templates_c/d2
          mkdir -p ./tmp/tcpdf
          mkdir -p ./tmp/climulti
          mkdir -p /tmp
          chmod a+rw ./tests/lib/geoip-files || true
          chmod a+rw ./plugins/*/tests/System/processed || true
          chmod a+rw ./plugins/*/tests/Integration/processed || true

      - name: Install dependencies
        run: |
          composer install --ignore-platform-reqs

      - name: Setup LAMP apache2
        run: |
          sudo systemctl start php7.4-fpm
          sudo a2enmod actions alias proxy_fcgi rewrite
          sudo cp /home/runner/work/matomo/matomo/.github/scripts/test.conf /etc/apache2/sites-available/
          sudo a2ensite test.conf
          sudo systemctl restart apache2
          curl localhost

      - name: set tmp and screenshot folder permission
        run: |
          sudo gpasswd -a "$USER" www-data
          sudo chown -R "$USER":www-data /home/runner/work/matomo/matomo/
          sudo chmod o+w /home/runner/work/matomo/matomo/
          sudo chmod -R 777 /home/runner/work/matomo/matomo/tmp
          sudo chmod -R 777 /tmp
          sudo chmod -R 777 /home/runner/work/matomo/matomo/tmp/templates_c
          sudo chmod -R 777 /home/runner/work/matomo/matomo/tests/UI

      - name: Test runing
        if: matrix.tests == 'UnitTests'
        run: |
           ./vendor/phpunit/phpunit/phpunit --configuration ./tests/PHPUnit/phpunit.xml --testsuite UnitTests

      - name: Test runing
        if: startsWith(matrix.tests,'SystemTests') || startsWith(matrix.tests,'IntegrationTests')
        run: |
          ./vendor/phpunit/phpunit/phpunit --configuration ./tests/PHPUnit/phpunit.xml --testsuite ${{ matrix.tests }}



